In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

print ("\n value of matrix\n",a) 
ainv = np.linalg.pinv(a)  #inverse of given matrix
print ("\n Value of inverse matrix a\n",ainv)

#property1
p1 = a * ainv 
print("\n value of p1 \n",p1)
p1f = p1 * a 
print ("\n value of p1f\n",p1f)
err1 = p1f - a 
print ("\n value of err1\n",err1)

#property2
p2 = ainv * a
print("\n value of p2 \n",p2)
p2f = p2 * ainv
print ("\n value of p2f\n",p2f)
err2 = p2f - ainv
print ("\n value of err2\n",err2)

#property3
p3 = p1.transpose()
print ("\n value of p3\n",p3)
err3 = p3 - p1
print ("\n value of err3\n",err3)

#property4
p4 = p2.transpose()
print ("\n value of p4\n",p4)
err4 = p4 - p2
print ("\n value of err4\n",err4)


 value of matrix
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Value of inverse matrix a
 [[-6.38888889e-01 -1.66666667e-01  3.05555556e-01]
 [-5.55555556e-02  1.38777878e-16  5.55555556e-02]
 [ 5.27777778e-01  1.66666667e-01 -1.94444444e-01]]

 value of p1 
 [[-6.38888889e-01 -3.33333333e-01  9.16666667e-01]
 [-2.22222222e-01  6.93889390e-16  3.33333333e-01]
 [ 3.69444444e+00  1.33333333e+00 -1.75000000e+00]]

 value of p1f
 [[-6.38888889e-01 -6.66666667e-01  2.75000000e+00]
 [-8.88888889e-01  3.46944695e-15  2.00000000e+00]
 [ 2.58611111e+01  1.06666667e+01 -1.57500000e+01]]

 value of err1
 [[ -1.63888889  -2.66666667  -0.25      ]
 [ -4.88888889  -5.          -4.        ]
 [ 18.86111111   2.66666667 -24.75      ]]

 value of p2 
 [[-6.38888889e-01 -3.33333333e-01  9.16666667e-01]
 [-2.22222222e-01  6.93889390e-16  3.33333333e-01]
 [ 3.69444444e+00  1.33333333e+00 -1.75000000e+00]]

 value of p2f
 [[4.08179012e-01 5.55555556e-02 2.80092593e-01]
 [1.23456790e-02 9.62964972e-32 1.85185185e-02]
 [1.